from math import prod

from database import CUTTING_TOOL_DATABASE, WORKPIECE_DATABASE


def recommended_cutting_tools(workpiece_material):
    scores = []
    for tool_material in CUTTING_TOOL_DATABASE:
        evaluation = evaluate_compatibility(workpiece_material, tool_material)
        if evaluation["is_compatible"]:
            scores.append((evaluation["score"], tool_material))

    if not scores:
        return WORKPIECE_DATABASE[workpiece_material]["recommended_tools"]

    scores.sort(reverse=True)
    return [tool for _, tool in scores[:3]]


def primary_recommended_tool(workpiece_material):
    return recommended_cutting_tools(workpiece_material)[0]


def _clamp(value, lower, upper):
    return max(lower, min(upper, value))


def _ratio(capacity, demand):
    return _clamp(capacity / max(demand, 0.01), 0.05, 1.25)


def _geometric_mean(values):
    return prod(values) ** (1 / len(values))


def _workpiece_demands(workpiece):
    hardness_demand = 250 + workpiece["hardness_bhn"] * 1.7
    toughness_demand = 5 + workpiece["toughness_index"] * 18
    abrasive_wear_demand = 35 + workpiece["abrasiveness"] * 40 + workpiece["wear_factor"] * 18

    heat_demand = 450 + (1 / max(workpiece["thermal_conductivity_w_mk"], 1)) * 2600
    heat_demand += workpiece["thermal_load"] * 120
    heat_demand = min(1350, heat_demand)

    chemical_demand = 300 + workpiece["chemical_reactivity"] * 650
    machinability_demand = 35 + (100 / max(workpiece["machinability_rating"], 10)) * 28

    return {
        "hardness": hardness_demand,
        "toughness": toughness_demand,
        "wear": abrasive_wear_demand,
        "heat": heat_demand,
        "chemical": chemical_demand,
        "machinability": machinability_demand
    }


def evaluate_compatibility(workpiece_material, tool_material):
    workpiece = WORKPIECE_DATABASE[workpiece_material]
    tool = CUTTING_TOOL_DATABASE[tool_material]
    demands = _workpiece_demands(workpiece)

    ratios = {
        "hardness": _ratio(tool["hot_hardness_c"], demands["hardness"]),
        "toughness": _ratio(tool["fracture_toughness_mpa"], demands["toughness"]),
        "wear": _ratio(tool["wear_resistance_index"], demands["wear"]),
        "heat": _ratio(tool["hot_hardness_c"], demands["heat"]),
        "chemical": _ratio(tool["oxidation_resistance_c"], demands["chemical"]),
        "machinability": _ratio(tool["max_cutting_speed"], demands["machinability"])
    }

    application_match = workpiece_material in tool["suitable_workpieces"]
    application_factor = 1.00 if application_match else 0.82
    compatibility_index = _geometric_mean(list(ratios.values())) * application_factor
    score = round(_clamp(compatibility_index * 100, 5, 100), 1)

    limiting_factor = min(ratios, key=ratios.get)
    is_compatible = (
        (application_match and score >= 68)
        or (tool_material in WORKPIECE_DATABASE[workpiece_material]["recommended_tools"] and score >= 72)
    )
    factor = round(_clamp(0.22 + compatibility_index * 0.88, 0.18, 1.08), 2)

    engineering_terms = {
        "hardness": "tool hot hardness versus workpiece hardness",
        "toughness": "tool fracture toughness versus interrupted-cut and ductility demand",
        "wear": "tool wear resistance versus abrasive wear demand",
        "heat": "hot-hardness retention versus heat generated by low thermal conductivity",
        "chemical": "oxidation and chemical stability versus reactivity/adhesion risk",
        "machinability": "maximum cutting speed versus machinability severity"
    }

    if is_compatible:
        reason = (
            f"{tool_material} is suitable for {workpiece_material}. "
            f"The compatibility score is {score}/100. The controlling factor is "
            f"{engineering_terms[limiting_factor]}, but the tool capacity remains acceptable. "
            f"Application basis: {tool['suitable_applications']}."
        )
    else:
        reason = (
            f"{tool_material} is not recommended for {workpiece_material}. "
            f"The compatibility score is {score}/100 because the limiting factor is "
            f"{engineering_terms[limiting_factor]}. "
            f"Use a tool with better {limiting_factor} capability for this workpiece."
        )

    return {
        "is_compatible": is_compatible,
        "score": score,
        "factor": factor,
        "reason": reason,
        "limiting_factor": limiting_factor,
        "property_ratios": {name: round(value, 2) for name, value in ratios.items()},
        "recommended_tools": recommended_cutting_tools_from_static_and_score(workpiece_material),
    }


def recommended_cutting_tools_from_static_and_score(workpiece_material):
    static_tools = WORKPIECE_DATABASE[workpiece_material]["recommended_tools"]
    ranked = []

    for tool_material, tool in CUTTING_TOOL_DATABASE.items():
        if workpiece_material in tool["suitable_workpieces"] or tool_material in static_tools:
            workpiece = WORKPIECE_DATABASE[workpiece_material]
            demands = _workpiece_demands(workpiece)
            ratios = [
                _ratio(tool["hot_hardness_c"], demands["hardness"]),
                _ratio(tool["fracture_toughness_mpa"], demands["toughness"]),
                _ratio(tool["wear_resistance_index"], demands["wear"]),
                _ratio(tool["hot_hardness_c"], demands["heat"]),
                _ratio(tool["oxidation_resistance_c"], demands["chemical"]),
                _ratio(tool["max_cutting_speed"], demands["machinability"]),
            ]
            ranked.append((_geometric_mean(ratios), tool_material))

    ranked.sort(reverse=True)
    tools = [tool for _, tool in ranked[:3]]
    return tools or static_tools
